# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
# feature_engineering/fraud_features/dbt_project.yml

name: "fraud_features"
version: "1.0.0"
config-version: 2

profile: "fraud_features"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  fraud_features:
    staging:
      +materialized: view # staging = vues légères
      +schema: fraud_detection
    features:
      +materialized: table # features = tables pour performance
      +schema: fraud_detection
